// Your other code...
const placements  = (placementsRes.data  ?? []) as unknown as PlacementRow[];
// Your other code...

const followUps   = (followUpsRes.data   ?? []) as unknown as FollowUpRow[];
// Your other code...